### ISSUE TITLE
pip install Fails

### ISSUE THREAD

**Issue by sloganking** [jeromepl/Locomotion#3]
### Issue

Running the command

```Bash
pip install -r requirements.txt
```

ends in error: 

```
Could not find a version that satisfies the requirement ipython==6.5.0 (from -r requirements.txt (line 18))
```

### System Environment

OS: Linux Mint 19.1 Tessa
KERNEL: 4.15.0-47-generic
CPU: Intel Core i7-4771 @ 3.50GHz
GPU: NVIDIA GeForce GTX 1080 Ti
GPU DRIVER: NVIDIA 418.43
RAM: 32 GB

**Comment by sloganking** [comment]
What OS has the successfully worked on?

**Comment by jeromepl** [comment]
Ah, yeah, sorry about that. I wasn't very thorough with my dependency management at the time and a lot of the dependencies listed in the `requirements.txt` file might not be necessary.
Specifically for `ipython`, you don't need it, so simply removing that item from the requirements file should fix this error (and hopefully all other dependencies are okay).

I was working on this project on a Windows machine, but hopefully everything should work on Linux with minimal work

**Comment by jeromepl** [comment]
Trying to reinstall all the dependencies now and it looks like you will need to upgrade to a newer tensorflow version as older ones such as 1.9 that I used at the time don't seem to be available on pip anymore.

**Comment by sloganking** [comment]
Removed ipython, still encountered some errors.

### Error and Fix 1:
I was getting errors with the ``-e git+https://`` requirements but fixed them by installing git with 
```
sudo apt install git
```

Though it could be assumed, you may want to consider adding git as a dependency to install in your ReadMe before running ``pip install -r requirements.txt``.


### Error and Fix 2:
Program repeatedly errored with
```
error: invalid command 'bdist_wheel'
```

Fixed by installing wheel with
```
pip install wheel
```

I recommend adding wheel to "requirements.txt"

### Current Errors:

```
examples/pybullet/pybullet.c:24:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pybullet
```

```
_posixsubprocess.c:16:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for subprocess32
```
```
_posixsubprocess.c:16:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Xhmvy0/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-HeGDPr-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-Xhmvy0/subprocess32/
```

Tried installing setuptools with ``pip install setuptools`` but it did not fix the issue.
